import { defineConfig } from 'eslint/config';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import tseslint from 'typescript-eslint';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import prettier from 'eslint-config-prettier';

export default defineConfig([
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      // Generated by scripts/gen-blur.mjs — never hand-edited, so never linted.
      'src/data/blur.generated.ts',
      'test-results/**',
      'playwright-report/**',
      'blob-report/**',
    ],
  },

  // Type-aware rules for the application source. `projectService` lets
  // typescript-eslint resolve each file's tsconfig itself, which matters here
  // because the Playwright specs and the app share one project.
  {
    files: ['**/*.ts', '**/*.tsx'],
    extends: [...tseslint.configs.strictTypeChecked],
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      /**
       * Numbers are allowed inside template literals. The rule exists to stop
       * objects and nullables being stringified into "[object Object]" or
       * "undefined"; a number has exactly one sensible string form, and
       * `${delay * 80}ms` in a style value or `${index + 1}` in a label is the
       * clearest way to write it. Objects, nullables and `any` stay banned.
       */
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: true },
      ],

      /**
       * A leading underscore marks a binding that exists only to be discarded —
       * the omit-by-destructuring idiom, `const { [key]: _dropped, ...rest }`,
       * which is how a key is removed without `delete`.
       */
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  // Build and measurement scripts are plain ESM JavaScript with no tsconfig, so
  // the type-aware rules cannot run on them. Linted, but untyped.
  {
    files: ['**/*.mjs', '**/*.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },

  {
    extends: [...nextCoreWebVitals],
    rules: {
      /**
       * jsx-a11y's full recommended set. Spread as bare rules rather than
       * extending `jsxA11y.flatConfigs.recommended`: eslint-config-next already
       * registers the jsx-a11y plugin, and a second registration is a hard
       * config error ("Cannot redefine plugin"). Next enables only a subset of
       * these, so this is a real widening, not a no-op.
       */
      ...jsxA11y.flatConfigs.recommended.rules,
      /**
       * Back to "error" now that both violations it flagged are gone: B11
       * (I18nProvider hydrating the locale from storage) in Task 6, and B4
       * (ThemeProvider guessing 'dark' then correcting itself) in Task 14.
       * Both were real bugs, and both produced a first render that disagreed
       * with the DOM the no-flash script had already written.
       */
      'react-hooks/set-state-in-effect': 'error',
    },
  },

  // Last: turns off every rule that only disagrees with Prettier about layout.
  prettier,
]);
