import { defineConfig } from "eslint/config";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";

export default defineConfig([
  {
    // Generated by scripts/gen-blur.mjs — never hand-edited, so never linted.
    ignores: ["src/data/blur.generated.ts"],
  },
  {
    extends: [...nextCoreWebVitals],
    rules: {
      /**
       * TEMPORARY — downgraded from error to warning.
       *
       * eslint-config-next@16 pulls in eslint-plugin-react-hooks@7, whose
       * set-state-in-effect rule correctly flags two bugs already tracked in
       * the register (docs/superpowers/specs/2026-07-27-mauri-dev-v2-design.md §2):
       *
       *   B11 — src/i18n/I18nProvider.tsx: locale hydrated from localStorage in
       *         an effect. Closed by Task 6, which deletes that effect entirely
       *         when the locale starts coming from the route.
       *   B4  — src/theme/ThemeProvider.tsx: initial state hardcoded 'dark',
       *         then re-set from storage in an effect. Closed by Task 14.
       *
       * The code is wrong, not the rule. This stays a warning only so the lint
       * gate keeps catching NEW violations in tasks 3-5, which cannot fix these
       * two because they do not touch those files.
       *
       * Task 13 MUST restore this to "error" once B4 and B11 are closed.
       */
      "react-hooks/set-state-in-effect": "warn",
    },
  },
]);
