// Generates tiny base64 LQIP blur placeholders for every raster image under
// public/projects/**. Output: src/data/blur.generated.ts (path -> dataURL map).
// Run with:  node scripts/gen-blur.mjs
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = fileURLToPath(new URL('..', import.meta.url));
const projectsDir = join(root, 'public', 'projects');
const RASTER = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif']);

async function walk(dir) {
  const out = [];
  for (const name of await readdir(dir)) {
    const full = join(dir, name);
    const s = await stat(full);
    if (s.isDirectory()) out.push(...(await walk(full)));
    else if (RASTER.has(extname(name).toLowerCase())) out.push(full);
  }
  return out;
}

const files = await walk(projectsDir);
const map = {};

for (const file of files) {
  const buf = await sharp(file)
    .resize(20, 20, { fit: 'inside' })
    .webp({ quality: 40 })
    .toBuffer();
  // Public URL path as referenced in the app (POSIX, leading slash).
  const publicPath = '/' + relative(join(root, 'public'), file).split('\\').join('/');
  map[publicPath] = `data:image/webp;base64,${buf.toString('base64')}`;
}

const body = `// AUTO-GENERATED by scripts/gen-blur.mjs — do not edit by hand.
// Tiny LQIP blur placeholders (base64) keyed by public image path.
/* eslint-disable */
export const blurMap: Record<string, string> = ${JSON.stringify(map, null, 2)};

/** Returns a blurDataURL for a public image path, or undefined if none exists. */
export function blurFor(src: string): string | undefined {
  return blurMap[src];
}
`;

await writeFile(join(root, 'src', 'data', 'blur.generated.ts'), body, 'utf8');
console.log(
  `Generated ${Object.keys(map).length} blur placeholders → src/data/blur.generated.ts`,
);
