// AUTO-GENERATED by scripts/gen-blur.mjs — do not edit by hand.
// Tiny LQIP blur placeholders (base64) keyed by public image path.
/* eslint-disable */
export const blurMap: Record<string, string> = {
  "/projects/ecommerce/1.webp": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAAwAPu1iqU2ppaQiMAgBMB2JaQDG9CFUz/F1igTQi8HAAP7rMbRjcydxLGtVZbK3/OyLYTaIwMaUfqL4S3NXRE9A/y/aW9c59byd1c5n8wMdZxIi3ny8F7F4yVEMnBGAAA==",
  "/projects/ecommerce/2.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoUAAwAPu1iqU2ppaQiMAgBMB2JaQAAXE7WJvhDBvHMVoAA/u/azW//JN9ZTivtrmPbs3pfG0D/gCe4TjYysFn4fl4VeSkAgFM6tL9KcAA=",
  "/projects/ecommerce/3.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAwAwCdASoUAAwAPu1iqk2ppaQiMAgBMB2JaWJJADc1naQAAP7wYxceHXUFp07WiyFnYVIICf2yVnxiVTWV4snSFAA=",
  "/projects/ecommerce/4.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAwAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JaQAAUqbZjCAAAP7SoCt3Z+OI5XUjrZ13gISdHBdUhz4AAAA=",
  "/projects/ml-scores/1.jpeg": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAwCdASoJABQAPu1iqU2ppaOiMAgBMB2JZQAAifANVpwAAP7vyVgBfhCCG0PsjI2kB4BLF53KvfZnNdMh//2SMVFEqAAA",
  "/projects/ml-scores/2.jpeg": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAABwAwCdASoJABQAPu1iqU2ppaQiMAgBMB2JZwDE2CICipJGHIQA/u6Xx4rkLTcK/BDHgAAA",
  "/projects/ml-scores/3.jpeg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAABwAwCdASoJABQAPu1iqU2ppaQiMAgBMB2JZwDG9DBfDAeyqgAA/u/IY9JRsT9K6wGu8EJO1baHzAAA",
  "/projects/ml-scores/4.jpeg": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoJABQAPu1iqU2ppaOiMAgBMB2JZwC+SDBsAAD+76MdIqjlCs+9okRLAPe9TAAA",
  "/projects/ml-scores/5.jpeg": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAwCdASoJABQAPu1iqU2ppaQiMAgBMB2JZQC7AB6Wc7WnYOwAAP7sTa+Guhw2taSSr1YZ5oo6npONJxxPjcCgIAA=",
  "/projects/pharmanet/1.jpeg": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAABQAwCdASoLABQAPu1mq04ppaQiMAgBMB2JTDwKaAJypHX3gAD+8AijjWH8X48kxdRSqMR1ELc9EEFgBlBl4yksOHB7OvucVre4gUAAAAA=",
  "/projects/pharmanet/10.jpeg": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAwCdASoMABQAPu1iqk4ppaQiMAgBMB2JYwCw7C0BvmASAAD+8Ai0AiTcKFS3yKXky3+VCgmHj+2WUHgh34FoI6KGvoM1DgFx3adewzo5VqD1t4ThMehbrWAAAA==",
  "/projects/pharmanet/11.jpeg": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAgCdASoKABQAPu1iqU2ppaQiMAgBMB2JZQAAeyAA/u/Ev7CWX/Aji2I7XX8WvoIl1wU0CAA=",
  "/projects/pharmanet/2.jpeg": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAwCdASoKABQAPu1iqU2ppaOiMAgBMB2JZWkfUI8T1wAA/vAmaQShh2fACWOEvMMMj5uayhZKbW6/EAA=",
  "/projects/pharmanet/3.jpeg": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwAwCdASoKABQAPu1iqU2ppaOiMAgBMB2JZQCdACIY/DSxHXzRVBoAAP6JS0Ep6yk7HIZWEKXHAFrjxhIbyiFnOOLXGvxFt8JL1qqPelQ+dORDbveipjAynhXwu9NvuMr6/EXySX02of0H8rXbwFYVnUg5tRC6WIr8oTkjCLNVAAAA",
  "/projects/pharmanet/4.jpeg": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAwCdASoLABQAPu1kqU2ppaQiMAgBMB2JZQCdAB6SBv0VhTX0AAD+3PyLgN2+TtEO6Ft9qQ4s1JCg1tK8howxWGtnoieu+yYKbh/LBAo5lHrczpwAAA==",
  "/projects/pharmanet/5.jpeg": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoKABQAPu1iqU2ppaOiMAgBMB2JZwAAXK+5EMARm0+cUAD+8d8MUNyt+2hehUaUJmMw927DpFerv+P4HNBxZwDDAwmCwD5C3NyDgAAA",
  "/projects/pharmanet/6.jpeg": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAwCdASoLABQAPu1krU2ppaSiMAgBMB2JYgABHuk+dRL2AAD+/TAGtghdw9wUgokqTDs2SEG7UXd0ptHz70H922XHyFj07fMA+FV6dYCjjn0w5dAgAA==",
  "/projects/pharmanet/7.jpeg": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABwAwCdASoLABQAPu1iqU2ppaOiMAgBMB2JZQC7ACKp9dIxpAAA/tzAKrAepugDr7yCPMyMtk6ZIwboLNhVs/rfyKCl9e6HcJgTC4AA",
  "/projects/pharmanet/8.jpeg": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQAwCdASoKABQAPu1krU2ppaSiMAgBMB2JYwCdMoAEZuM6EAD+76KWtMj7LhqAIN9czSobkj0gUCGdvBHZJKU8b3gskJlcQAA=",
  "/projects/pharmanet/9.jpeg": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAwCdASoLABQAPu1iqU2ppaOiMAgBMB2JZQCsADKHM1QAAP7vobJW6x+v3H6TTRcn0chP5TcwAA==",
  "/projects/presencia/1.png": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoUAAkAPu1iqU2ppaOiMAgBMB2JZwAAUqt6sMwklN8hAAD+6QaJT+KokEKpO+bsMu9dVRDERoePhAAA",
  "/projects/presencia/2.png": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoUAAkAPu1iqU2ppaOiMAgBMB2JZQDG9B6PlYH+HmQAAP7swZR/SHEMA3Mb/DXvtvM7gJsAbvM4GA09M9iuAAAA",
  "/projects/presencia/3.png": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABwAwCdASoUAAkAPu1iqU2ppaQiMAgBMB2JZQDE2B6QNqbp5AAA/uXupXC8GxjfpvNArMirfIEva6M2Q+WKM0JzLcysmAAA",
  "/projects/presencia/4.png": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAAkAPu1iqU2ppaQiMAgBMB2JZwDE2CPP0iS3yMGWYgAA/uXupXC59oA3O5DduY9G/o1FxzGh9rQ0QVfr06pNmdiL7z/eN25Fw5lTr7G0YAAA",
  "/projects/pulse-analytics/1.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JZQDCgCHe8Xuj0gqrdAAA/u6KfnbB4uawpZ7Az/JJ8I7ekE3luzAk0w1zs/YHVMqa4ySloAapoAAA",
  "/projects/pulse-analytics/2.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoUAAwAPu1kq04ppaQiMAgBMB2JYwAAW3+uivFDO0AA/u6Io5KQQKbg0QLM6ZH3dZ0ywNZfd8HmM/LwlKA3wnwYGJxooQv+E6LaWfjAAAA=",
  "/projects/pulse-analytics/3.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAwCdASoUAAwAPu1kqU2ppaQiMAgBMB2JZ2VuU0ATkdvC1QAA/vA+YdIgbq1dZhBrvl009mE2Ac9g4CyxAAAA",
  "/projects/skin-beauty/1.jpg": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwAwCdASoKABQAPu1kqU4ppaOiMAgBMB2JaADCgCFr/Qjs6RAA/vHRorObla11JuQl/MnTV/m9mY50MG09BVC9jSxxneh9wdUoKqEe6DxS2oAA",
  "/projects/skin-beauty/2.jpg": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACQAwCdASoJABQAPu1kqU2ppaQiMAgBMB2JQAALfcijURLjtCd4AP7x3BIaolu74b+X3GYAeCs7I74O1f6KidOdLOVXoyT7bBFHuay0FJmUx4p3Bf7rxVhy6FmdR8Qq5zIay1cnjO+MJzOvcmfwX/K4hcP0j2LWf8myAAAA",
  "/projects/skin-beauty/3.jpg": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwAwCdASoKABQAPu1iqU2ppaOiMAgBMB2JYgC7ACK4RPQgDkkE9L4AAP6bG65RVsvZMhic+c0E4keEAD44QaSpu40ck0simmkVtK3rAM55QAvZ4W2VgM+u4MiMsZOMI17D61U45bgD3nXE4rpDPvCTdZBMddLSmvuIkEkzM1V65KAA",
  "/projects/skin-beauty/4.jpg": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwAwCdASoMABQAPu1iqU2ppaQiMAgBMB2JagCpAXAAK4w5Ta84hAD9qKYRO/7PAl4XeNBRc8f5WcLokG3kxTGkacIEZ9vcfvG/JG1WRHqxSB8PQkKk3rN2yhIjODj0VIFGrT80zBxen/HOF8xlo9WtOKq+lTb+p0y8ev4cwAAAAA==",
  "/projects/skin-beauty/5.jpg": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwBACdASoKABQAPu1iqU2ppaQiMAgBMB2JYgCdACLs7XpBGGtwWmDrNnAA3MMrdm/OXsr8MdODvGKQxrHx6mA8J1KE8GPrE7cel7ITUdu0qAIWrOx4AUX7tVjw8q9L7d9INE7BZnadB+unfhT4urQAAAA=",
  "/projects/skin-beauty/6.jpg": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoMABQAPu1krU6ppaSiMAgBMB2JZgC/OCHpSquS0vz0T8AA+6WyUiWSuwb49+Q7ubUI40nJbYfng2NIntd+SF6r+Ady6IC0uZt81P+9NJlaOG7dNy/73Mu2vqkgmarJif9a6WcnTQU3VES6O7HgAA==",
  "/projects/skin-beauty/cover.jpg": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACQAwCdASoJABQAPu1kqU2ppaQiMAgBMB2JQAALfcijURLjtCd4AP7x3BIaolu74b+X3GYAeCs7I74O1f6KidOdLOVXoyT7bBFHuay0FJmUx4p3Bf7rxVhy6FmdR8Qq5zIay1cnjO+MJzOvcmfwX/K4hcP0j2LWf8myAAAA",
  "/projects/swift-eats/1.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoJABQAPu1iqU2ppaOiMAgBMB2JQBfnBDsw771JYEGogAD+78WclegrAHwZFWWrgRcHUSrVJBuaWhx8UTwV0+IM96DlMdSDrXpDfxi3GLUSDqR0cKAwxoAA",
  "/projects/swift-eats/2.webp": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoJABQAPu1krU6ppaSiMAgBMB2JaACdOUAA8YNGysJyQwiOAADMg3ucG0gFKlqmHTF3jp62p6WkhZHyaYM+SbHmpXC+gPZWqlbZ8SpK5KKIRsx40OrYRLCaKW98V573b3/sR0dO6ha2/7qGSpAAAA==",
  "/projects/swift-eats/3.webp": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoJABQAPu1iqU2ppaOiMAgBMB2JYgB3AA0a6kPRf/n3NtkQQAD+/TVemRPDTWzzFW3Uqkj+2LLiRVrfV4Dm7d54/PclTkmpIatAHbH6DICLfG8UwEV/U3MhRBpFTwIMllGeJAAA",
  "/projects/swift-eats/4.webp": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4WAoAAAAQAAAACAAAEwAAQUxQSBIAAAABD/D0/4iIIBBIzt98goj+ZxNWUDggTgAAADADAJ0BKgkAFAA+7WKpTamlo6IwCAEwHYlnAACDnSrmOwAA/u/zP84zfeTwad3Ii14gXwN9rew6q6ejlSmok5er1F44BBZRQycE7BxAAA=="
};

/** Returns a blurDataURL for a public image path, or undefined if none exists. */
export function blurFor(src: string): string | undefined {
  return blurMap[src];
}
